apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m7z7f8lpn-java-springboot
  janus-idp.io/tekton: m7z7f8lpn-java-springboot
  backstage.io/kubernetes-id: m7z7f8lpn-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m7z7f8lpn-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
